services:
  postgres:
    container_name: postgresDB
    image: postgres:17.5-alpine3.22
    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: yu71
      POSTGRES_PASSWORD: S3cret
      POSTGRES_SCHEMA: employees
      PGDATA: ./postgres_data
    volumes:
      #      - ./sql/:/docker-entrypoint-initdb.d/
      #      - ./postgres:/data/postgres
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      postgres-network:
        ipv4_address: 172.28.1.2
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:9.4.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      postgres-network:
        ipv4_address: 172.28.1.3
    restart: unless-stopped

networks:
  postgres-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  postgres:
  pgadmin:
