services:
  postgres:
    container_name: postgresDB
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-employees}
      POSTGRES_USER: ${POSTGRES_USER:-yuji}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-S3cret}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA:-employees}
      PGDATA: ./postgres_data
    volumes:
      #      - ./sql/:/docker-entrypoint-initdb.d/
      #      - ./postgres:/data/postgres
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.11.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
